# Default properties file

spring:
  profiles:
    active: ${SCOPE_SUFFIX} # Comma-separated list of active profiles. Can be overridden by a command line switch.
  resources:
    add-mappings: false # Whether to enable default resource handling.
  mvc:
    throw-exception-if-no-handler-found: true # Whether a "NoHandlerFoundException" should be thrown if no Handler was found to process a request.
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  sql:
    init:
      mode: always
      data-locations: classpath:setup.sql
      continue-on-error: true
  boot:
    admin:
      client:
        url: http://localhost:8081
        instance:
          management-url: "http://localhost:8080/actuator"
          health-url: "http://localhost:8080/actuator/health"
          service-url: "http://localhost:8080"
          management-base-url: "http://localhost:8080/actuator"

db:
  host: localhost:3306
  username: admin
  password: admin
  name: blocksdb
  url: jdbc:mysql://%s/%s?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
  driver:
    name: com.mysql.cj.jdbc.Driver

server:
  error:
    include-stacktrace: never
  compression:
    enabled: true # Whether response compression is enabled.
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed.

app:
  title: springbootbuildingblocks
  description: @project.description@
  version: @project.version@

management:
  health:
    db:
      enabled: true
  endpoint:
    health:
      show-details: always
    httptrace:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
  info:
    env:
      enabled: true
