# Properties file for local/dev environment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  sql:
    init:
      mode: always
      data-locations: classpath:setup.sql
      continue-on-error: true
db:
  host: localhost:3306
  username: admin
  password: admin
  name: blocksdb
  url: jdbc:mysql://%s/%s?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
  driver:
    name: com.mysql.cj.jdbc.Driver